{
    'name': 'account invoice addons',
    'description': 'account invoice addons',
    'author': '1di0t',
    'depends': ['base',
                'account',
                'hr_expense',
                'product',
                'purchase',
                'sale',
                'stock',
                'osbzr_account',
                'fleet',
                'account_hierarchy',
                'account_period',
                'l10n_cn_voucher',
                'stock_account2',
                'account_period'],
    'application': True,
    'data': [
        'views/account_invoice.xml',
        'views/account_payment.xml',
        'views/purchase.xml',
        'views/sale.xml',
        'views/stock.xml',
        'views/hr_expense.xml',
        'views/stock_pack_operation.xml',
        'views/res_company.xml',
        'views/stock_picking.xml',
        'views/actual_invoice_view.xml',
        'views/stock_move.xml',
        'views/fleet_vehicle.xml',
        'views/hr_exployee.xml',
        'views/ac_tb_group.xml',
        'views/account_move.xml',
        'static/src/xml/account.xml',
        'wizard/hr_expense_payment.xml',
        'security/account_security.xml',
        'security/stock_security.xml',
        'security/ir.model.access.csv',
    ],
}
